"use client";

import { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "motion/react";
import {
  Upload,
  FileText,
  AlertCircle,
  ChevronDown,
  ExternalLink,
  Shield,
  Dna,
  Lock,
  Sparkles,
  HeartPulse,
  ArrowDown,
  Quote,
} from "lucide-react";
import CompatibilityReport from "../../components/CompatibilityReport";
import NavBar from "../../components/NavBar";
import Footer from "../../components/Footer";
import ProtectedRoute from "../../components/ProtectedRoute";

const API = process.env.NEXT_PUBLIC_API_URL || "http://localhost:5000";

/* ── FAQ ── */
const FAQ_DATA = [
  {
    q: "What is pharmacogenomic compatibility testing?",
    a: "It analyzes both partners' genetic variants in drug-metabolizing genes (like CYP2D6, CYP2C19, DPYD) to predict how your future children may respond to common medications — helping families plan ahead for safer, personalized treatments.",
  },
  {
    q: "What file format do I need?",
    a: "Standard VCF (Variant Call Format) files — .vcf, .vcf.gz, or .vcf.bgz. These are generated by most genetic testing services, clinical sequencing labs, and direct-to-consumer platforms.",
  },
  {
    q: "Is my genetic data safe?",
    a: "Your VCF files are processed in-memory and never stored. Analysis happens in a single session, all data is discarded once your report is generated. We follow strict data minimization principles.",
  },
  {
    q: "How accurate are the predictions?",
    a: "Our models use established Mendelian inheritance patterns and CPIC clinical guidelines. While predictions reflect theoretical probabilities, real-world outcomes can vary. Always consult a genetic counselor for clinical decisions.",
  },
  {
    q: "Can I share the report with my doctor?",
    a: "Yes — download a comprehensive PDF report with gene-by-gene breakdowns, risk assessments, and plain-English explanations. Perfect for discussing with your healthcare provider or genetic counselor.",
  },
];

/* ── References ── */
const REFERENCES = [
  {
    title: "CPIC Guidelines for Pharmacogenomics",
    journal: "Clinical Pharmacogenetics Implementation Consortium",
    url: "https://cpicpgx.org/guidelines/",
  },
  {
    title: "PharmGKB: Pharmacogenomics Knowledge Base",
    journal: "Stanford University",
    url: "https://www.pharmgkb.org/",
  },
  {
    title: "Pharmacogenomics in Reproductive Medicine",
    journal: "Nature Reviews Genetics, 2023",
    url: "https://www.nature.com/articles/s41576-023-00598-8",
  },
];

/* ── FAQ Item ── */
function FAQItem({ item, isOpen, onClick }) {
  return (
    <div className="border-b border-[#0b1e40]/6 last:border-0">
      <button
        onClick={onClick}
        className="w-full flex items-center justify-between py-5 text-left group"
      >
        <span className="text-[15px] font-medium text-[#0b1e40] pr-8 group-hover:text-[#5a7a52] transition-colors">
          {item.q}
        </span>
        <ChevronDown
          className={`w-4 h-4 shrink-0 text-[#a9bb9d] transition-transform duration-300 ${isOpen ? "rotate-180" : ""}`}
        />
      </button>
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3, ease: "easeInOut" }}
            className="overflow-hidden"
          >
            <p className="pb-5 text-sm text-[#5a6070] leading-relaxed pr-12">
              {item.a}
            </p>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

/* ══════════════════════════════════════════════════ */
export default function IVFPage() {
  const [step, setStep] = useState("upload");
  const [userFile, setUserFile] = useState(null);
  const [partnerFile, setPartnerFile] = useState(null);
  const [results, setResults] = useState(null);
  const [error, setError] = useState(null);
  const [openFAQ, setOpenFAQ] = useState(null);
  const uploadRef = useRef(null);

  const handleUserFile = (e) => {
    if (e.target.files?.[0]) setUserFile(e.target.files[0]);
  };
  const handlePartnerFile = (e) => {
    if (e.target.files?.[0]) setPartnerFile(e.target.files[0]);
  };

  const handleAnalyze = async () => {
    if (!userFile || !partnerFile) return;
    setStep("analyzing");
    setError(null);
    const formData = new FormData();
    formData.append("user_vcf", userFile);
    formData.append("partner_vcf", partnerFile);
    try {
      const res = await fetch(`${API}/api/couple-analysis`, {
        method: "POST",
        body: formData,
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Analysis failed");
      setResults(data);
      setStep("results");
    } catch (err) {
      console.error(err);
      setError(err.message);
      setStep("upload");
    }
  };

  const scrollToUpload = () =>
    uploadRef.current?.scrollIntoView({ behavior: "smooth", block: "center" });

  return (
    <ProtectedRoute>
      <style>{`
        @keyframes gentlePulse {
          0%, 100% { opacity: 0.45; }
          50% { opacity: 0.7; }
        }
        @keyframes driftUp {
          0%, 100% { transform: translateY(0); }
          50% { transform: translateY(-8px); }
        }
        @keyframes helixSpin {
          0% { transform: rotate(0deg); }
          100% { transform: rotate(360deg); }
        }
      `}</style>

      <div className="min-h-screen bg-white" style={{ fontFamily: "'Mulish', sans-serif" }}>
        <NavBar />

        {step === "upload" && (
          <>
            {/* ════════════════════════════════════
                HERO — Centered, warm, intimate
            ════════════════════════════════════ */}
            <section className="relative overflow-hidden bg-gradient-to-b from-[#f6f8f4] via-[#f9faf7] to-white">
              {/* Decorative orbs */}
              <div
                className="absolute pointer-events-none"
                style={{
                  width: 500, height: 500, top: -120, left: -80,
                  background: "radial-gradient(circle, rgba(169,187,157,0.12) 0%, transparent 65%)",
                  filter: "blur(80px)",
                }}
              />
              <div
                className="absolute pointer-events-none"
                style={{
                  width: 400, height: 400, bottom: -60, right: -60,
                  background: "radial-gradient(circle, rgba(11,30,64,0.04) 0%, transparent 65%)",
                  filter: "blur(60px)",
                }}
              />

              {/* Floating helix decoration */}
              <div
                className="absolute right-[10%] top-[20%] opacity-[0.04] pointer-events-none select-none"
                style={{ animation: "driftUp 8s ease-in-out infinite" }}
              >
                <svg width="180" height="280" viewBox="0 0 180 280" fill="none" xmlns="http://www.w3.org/2000/svg">
                  <path d="M90 0C90 0 20 40 20 70C20 100 160 100 160 130C160 160 20 160 20 190C20 220 160 220 160 250C160 265 130 280 90 280" stroke="#0b1e40" strokeWidth="2.5" strokeLinecap="round"/>
                  <path d="M90 0C90 0 160 40 160 70C160 100 20 100 20 130C20 160 160 160 160 190C160 220 20 220 20 250C20 265 50 280 90 280" stroke="#a9bb9d" strokeWidth="2.5" strokeLinecap="round"/>
                  {/* Rungs */}
                  {[35, 65, 100, 130, 165, 195, 230].map((y, i) => (
                    <line key={i} x1="45" y1={y} x2="135" y2={y} stroke="#0b1e40" strokeWidth="1" opacity="0.08" />
                  ))}
                </svg>
              </div>

              <div className="relative z-10 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pt-32 pb-24 text-center">
                {/* Pill badge */}
                <motion.div
                  initial={{ opacity: 0, y: 12 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5 }}
                  className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-[#a9bb9d]/10 border border-[#a9bb9d]/20 text-[#5a7a52] text-[11px] font-semibold tracking-wide uppercase mb-6"
                >
                  <HeartPulse className="w-3.5 h-3.5" />
                  Family Pharmacogenomics
                </motion.div>

                {/* Headline */}
                <motion.h1
                  initial={{ opacity: 0, y: 16 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.6, delay: 0.1 }}
                  className="text-[#0b1e40] leading-[1.1] tracking-tight mb-6"
                  style={{ fontWeight: 500, fontSize: "clamp(2rem, 4.5vw, 3.6rem)" }}
                >
                  Before they take their
                  <br />
                  first medicine — <span className="text-[#a9bb9d]">know</span>.
                </motion.h1>

                {/* Subtext */}
                <motion.p
                  initial={{ opacity: 0, y: 16 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.6, delay: 0.2 }}
                  className="text-[#5a6070] text-base sm:text-lg leading-relaxed max-w-xl mx-auto mb-10 font-light"
                >
                  Predict how your future children may respond to medications
                  by comparing both partners' pharmacogenomic profiles.
                  <br className="hidden sm:block" />
                  One test today, a lifetime of safer prescriptions.
                </motion.p>

                {/* CTA */}
                <motion.div
                  initial={{ opacity: 0, y: 16 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.6, delay: 0.3 }}
                  className="flex flex-col items-center gap-4"
                >
                  <button
                    onClick={scrollToUpload}
                    className="group inline-flex items-center gap-2.5 bg-[#5a7a52] text-white rounded-full text-sm font-semibold tracking-wide transition-all duration-300 shadow-lg shadow-[#a9bb9d]/25 hover:shadow-xl hover:shadow-[#a9bb9d]/35 hover:-translate-y-0.5 hover:bg-[#4a6a43]"
                    style={{ padding: "14px 36px" }}
                  >
                    Begin Your Analysis
                    <ArrowDown className="w-4 h-4 transition-transform group-hover:translate-y-0.5" />
                  </button>
                  <span className="text-xs text-[#5a6070]/60">
                    No data stored · Results in seconds
                  </span>
                </motion.div>
              </div>
            </section>

            {/* ════════════════════════════════════
                NARRATIVE STRIP — Inline trust
            ════════════════════════════════════ */}
            <section className="border-y border-[#0b1e40]/5 bg-white">
              <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-5 flex flex-wrap items-center justify-center gap-x-10 gap-y-3 text-[13px] text-[#5a6070]">
                <span className="flex items-center gap-2">
                  <Dna className="w-4 h-4 text-[#a9bb9d]" /> 12+ pharmacogenes analyzed
                </span>
                <span className="hidden sm:block w-px h-4 bg-[#0b1e40]/8" />
                <span className="flex items-center gap-2">
                  <Shield className="w-4 h-4 text-[#a9bb9d]" /> CPIC-aligned models
                </span>
                <span className="hidden sm:block w-px h-4 bg-[#0b1e40]/8" />
                <span className="flex items-center gap-2">
                  <Lock className="w-4 h-4 text-[#a9bb9d]" /> Zero data retention
                </span>
              </div>
            </section>

            {/* ════════════════════════════════════
                HOW IT WORKS — Horizontal timeline
            ════════════════════════════════════ */}
            <section className="py-24 bg-white">
              <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
                <p className="text-[10.5px] font-semibold tracking-[0.2em] uppercase text-[#a9bb9d] text-center mb-2">
                  How it works
                </p>
                <h2 className="text-center text-2xl sm:text-[1.75rem] font-medium text-[#0b1e40] mb-16">
                  From upload to insight in three steps
                </h2>

                {/* Timeline */}
                <div className="relative">
                  {/* Line (desktop) */}
                  <div className="hidden md:block absolute top-6 left-[8%] right-[8%] h-px bg-[#a9bb9d]/25" />

                  <div className="grid grid-cols-1 md:grid-cols-3 gap-12 md:gap-8">
                    {[
                      {
                        num: "1",
                        title: "Upload both VCFs",
                        desc: "Drop in your and your partner's genetic variant files. We support targeted panels through whole genomes.",
                      },
                      {
                        num: "2",
                        title: "Mendelian analysis",
                        desc: "Our engine models allele inheritance across 12+ drug-metabolizing genes using CPIC-standard logic.",
                      },
                      {
                        num: "3",
                        title: "Actionable report",
                        desc: "Get a clear breakdown of your children's predicted drug response profiles — with a downloadable PDF.",
                      },
                    ].map((s, i) => (
                      <motion.div
                        key={s.num}
                        initial={{ opacity: 0, y: 24 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true, margin: "-50px" }}
                        transition={{ duration: 0.5, delay: i * 0.12 }}
                        className="flex flex-col items-center md:items-center text-center"
                      >
                        {/* Circle */}
                        <div className="w-12 h-12 rounded-full bg-[#5a7a52] text-white flex items-center justify-center text-sm font-bold mb-5 shadow-sm shadow-[#a9bb9d]/20 relative z-10">
                          {s.num}
                        </div>
                        <h3 className="text-[15px] font-semibold text-[#0b1e40] mb-2">
                          {s.title}
                        </h3>
                        <p className="text-sm text-[#5a6070] leading-relaxed max-w-[280px]">
                          {s.desc}
                        </p>
                      </motion.div>
                    ))}
                  </div>
                </div>
              </div>
            </section>

            {/* ════════════════════════════════════
                UPLOAD CARD
            ════════════════════════════════════ */}
            <section ref={uploadRef} className="py-20 bg-[#f6f8f4]">
              <div className="max-w-2xl mx-auto px-4 sm:px-6">
                <motion.div
                  initial={{ opacity: 0, y: 24 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.5 }}
                  className="bg-white rounded-[28px] shadow-2xl shadow-[#0b1e40]/[0.04] border border-[#0b1e40]/[0.04] overflow-hidden"
                >
                  <div className="p-8 sm:p-10">
                    {/* Visual: two circles linked */}
                    <div className="flex items-center justify-center gap-3 mb-7">
                      <div className="w-10 h-10 rounded-full bg-[#0b1e40]/[0.06] flex items-center justify-center text-[11px] font-bold text-[#0b1e40]/60">
                        A
                      </div>
                      <div className="flex items-center gap-1">
                        <div className="w-5 h-px bg-[#a9bb9d]/40" />
                        <HeartPulse className="w-4 h-4 text-[#a9bb9d]" />
                        <div className="w-5 h-px bg-[#a9bb9d]/40" />
                      </div>
                      <div className="w-10 h-10 rounded-full bg-[#0b1e40]/[0.06] flex items-center justify-center text-[11px] font-bold text-[#0b1e40]/60">
                        B
                      </div>
                    </div>

                    <h2 className="text-center text-lg font-semibold text-[#0b1e40] mb-1">
                      Upload genetic data
                    </h2>
                    <p className="text-center text-sm text-[#5a6070] mb-8">
                      Both partners' VCF files are required
                    </p>

                    {/* Dropzones */}
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6">
                      {/* User */}
                      <label
                        className={`cursor-pointer border-2 border-dashed rounded-2xl p-6 text-center transition-all duration-200 relative group block ${
                          userFile
                            ? "border-[#a9bb9d] bg-[#a9bb9d]/[0.04]"
                            : "border-[#0b1e40]/8 hover:border-[#a9bb9d]/40 hover:bg-[#f6f8f4]"
                        }`}
                      >
                        <input
                          type="file"
                          onChange={handleUserFile}
                          accept=".vcf,.vcf.gz,.vcf.bgz"
                          className="sr-only"
                        />
                        <div
                          className={`w-10 h-10 rounded-full flex items-center justify-center mx-auto mb-3 transition-colors ${
                            userFile
                              ? "bg-[#a9bb9d]/15 text-[#5a7a52]"
                              : "bg-[#0b1e40]/[0.04] text-[#0b1e40]/25 group-hover:text-[#5a7a52]"
                          }`}
                        >
                          <Upload className="w-5 h-5" />
                        </div>
                        <p className="text-[10px] font-bold tracking-[0.15em] uppercase text-[#5a7a52] mb-1.5">
                          Partner A
                        </p>
                        {userFile ? (
                          <p className="text-[#5a7a52] font-medium text-sm flex items-center justify-center gap-1.5">
                            <FileText className="w-3.5 h-3.5" />
                            {userFile.name}
                          </p>
                        ) : (
                          <>
                            <p className="text-[#0b1e40] font-medium text-sm">
                              Choose file
                            </p>
                            <p className="text-[#5a6070]/40 text-xs mt-0.5">
                              .vcf · .vcf.gz · .vcf.bgz
                            </p>
                          </>
                        )}
                      </label>

                      {/* Partner */}
                      <label
                        className={`cursor-pointer border-2 border-dashed rounded-2xl p-6 text-center transition-all duration-200 relative group block ${
                          partnerFile
                            ? "border-[#a9bb9d] bg-[#a9bb9d]/[0.04]"
                            : "border-[#0b1e40]/8 hover:border-[#a9bb9d]/40 hover:bg-[#f6f8f4]"
                        }`}
                      >
                        <input
                          type="file"
                          onChange={handlePartnerFile}
                          accept=".vcf,.vcf.gz,.vcf.bgz"
                          className="sr-only"
                        />
                        <div
                          className={`w-10 h-10 rounded-full flex items-center justify-center mx-auto mb-3 transition-colors ${
                            partnerFile
                              ? "bg-[#a9bb9d]/15 text-[#5a7a52]"
                              : "bg-[#0b1e40]/[0.04] text-[#0b1e40]/25 group-hover:text-[#5a7a52]"
                          }`}
                        >
                          <Upload className="w-5 h-5" />
                        </div>
                        <p className="text-[10px] font-bold tracking-[0.15em] uppercase text-[#5a7a52] mb-1.5">
                          Partner B
                        </p>
                        {partnerFile ? (
                          <p className="text-[#5a7a52] font-medium text-sm flex items-center justify-center gap-1.5">
                            <FileText className="w-3.5 h-3.5" />
                            {partnerFile.name}
                          </p>
                        ) : (
                          <>
                            <p className="text-[#0b1e40] font-medium text-sm">
                              Choose file
                            </p>
                            <p className="text-[#5a6070]/40 text-xs mt-0.5">
                              .vcf · .vcf.gz · .vcf.bgz
                            </p>
                          </>
                        )}
                      </label>
                    </div>

                    {error && (
                      <div className="mb-4 p-3 bg-red-50 text-red-700 text-sm rounded-xl flex items-center gap-2">
                        <AlertCircle className="w-4 h-4 shrink-0" />
                        {error}
                      </div>
                    )}

                    <button
                      onClick={handleAnalyze}
                      disabled={!userFile || !partnerFile}
                      className="w-full bg-[#5a7a52] text-white py-3.5 rounded-full font-semibold text-sm tracking-wide hover:bg-[#4a6a43] disabled:opacity-35 disabled:cursor-not-allowed transition-all duration-300 flex items-center justify-center gap-2 shadow-md shadow-[#a9bb9d]/25 hover:shadow-lg hover:shadow-[#a9bb9d]/35"
                    >
                      <Sparkles className="w-4 h-4" />
                      Analyze Compatibility
                    </button>
                  </div>

                  <div className="bg-[#fafbf9] px-8 py-3.5 border-t border-[#0b1e40]/[0.04] text-center text-xs text-[#5a6070]/70">
                    Files processed in-memory · Nothing stored · Results in seconds
                  </div>
                </motion.div>
              </div>
            </section>

            {/* ════════════════════════════════════
                EXPERT QUOTE — Real person
            ════════════════════════════════════ */}
            <section className="py-24 bg-white">
              <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
                <motion.div
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.6 }}
                  className="relative"
                >
                  {/* Oversized quote mark */}
                  <Quote className="w-10 h-10 text-[#a9bb9d]/25 mb-5 -scale-x-100" strokeWidth={1.5} />

                  <blockquote
                    className="text-[#0b1e40] leading-[1.75] mb-6"
                    style={{
                      fontWeight: 300,
                      fontSize: "clamp(1.05rem, 1.8vw, 1.3rem)",
                      fontStyle: "italic",
                    }}
                  >
                    "The goal of pharmacogenomics is to get the right drug, at the
                    right dose, to the right patient, at the right time. When we
                    can anticipate a child's drug metabolism before they're even
                    born, we fundamentally change the safety equation."
                  </blockquote>

                  <div className="flex items-center gap-3">
                    <div className="w-px h-8 bg-[#a9bb9d]" />
                    <div>
                      <p className="text-sm font-semibold text-[#0b1e40]">
                        Dr. Mary V. Relling
                      </p>
                      <p className="text-xs text-[#5a6070]">
                        Chair of Pharmaceutical Sciences, St. Jude Children's Research Hospital &middot; Co-founder of CPIC
                      </p>
                    </div>
                  </div>
                </motion.div>
              </div>
            </section>

            {/* ════════════════════════════════════
                WHAT WE LOOK AT — Gene grid
            ════════════════════════════════════ */}
            <section className="py-20 bg-[#f6f8f4]">
              <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
                <p className="text-[10.5px] font-semibold tracking-[0.2em] uppercase text-[#a9bb9d] text-center mb-2">
                  Coverage
                </p>
                <h2 className="text-center text-2xl font-medium text-[#0b1e40] mb-4">
                  Genes we analyze
                </h2>
                <p className="text-center text-sm text-[#5a6070] max-w-lg mx-auto mb-12">
                  Each gene below controls how the body processes specific drug families.
                  We model Mendelian inheritance for every one.
                </p>

                <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-3">
                  {[
                    { gene: "CYP2D6", drugs: "Antidepressants, opioids" },
                    { gene: "CYP2C19", drugs: "PPIs, clopidogrel" },
                    { gene: "CYP2C9", drugs: "Warfarin, NSAIDs" },
                    { gene: "CYP3A5", drugs: "Tacrolimus, statins" },
                    { gene: "SLCO1B1", drugs: "Statin transport" },
                    { gene: "DPYD", drugs: "Fluoropyrimidine chemo" },
                    { gene: "TPMT", drugs: "Azathioprine, 6-MP" },
                    { gene: "NAT2", drugs: "Isoniazid, hydralazine" },
                    { gene: "VKORC1", drugs: "Warfarin sensitivity" },
                    { gene: "UGT1A1", drugs: "Irinotecan, atazanavir" },
                    { gene: "HLA-B", drugs: "Abacavir, carbamazepine" },
                    { gene: "G6PD", drugs: "Primaquine, rasburicase" },
                  ].map((g) => (
                    <div
                      key={g.gene}
                      className="bg-white rounded-xl p-4 border border-[#0b1e40]/[0.04] hover:border-[#a9bb9d]/30 transition-colors"
                    >
                      <p className="text-sm font-bold text-[#0b1e40] font-mono mb-0.5">
                        {g.gene}
                      </p>
                      <p className="text-[11px] text-[#5a6070] leading-snug">
                        {g.drugs}
                      </p>
                    </div>
                  ))}
                </div>
              </div>
            </section>

            {/* ════════════════════════════════════
                FAQ
            ════════════════════════════════════ */}
            <section className="py-24 bg-white">
              <div className="max-w-2xl mx-auto px-4 sm:px-6 lg:px-8">
                <p className="text-[10.5px] font-semibold tracking-[0.2em] uppercase text-[#a9bb9d] text-center mb-2">
                  Questions
                </p>
                <h2 className="text-center text-2xl font-medium text-[#0b1e40] mb-12">
                  Frequently asked
                </h2>

                <div className="border-t border-[#0b1e40]/6">
                  {FAQ_DATA.map((item, i) => (
                    <FAQItem
                      key={i}
                      item={item}
                      isOpen={openFAQ === i}
                      onClick={() => setOpenFAQ(openFAQ === i ? null : i)}
                    />
                  ))}
                </div>
              </div>
            </section>

            {/* ════════════════════════════════════
                REFERENCES — Minimal
            ════════════════════════════════════ */}
            <section className="py-16 bg-[#f6f8f4] border-t border-[#0b1e40]/[0.04]">
              <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
                <p className="text-[10px] font-semibold tracking-[0.2em] uppercase text-[#a9bb9d] mb-6">
                  References
                </p>
                <div className="space-y-4">
                  {REFERENCES.map((r, i) => (
                    <a
                      key={i}
                      href={r.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="group flex items-start gap-3 text-sm"
                    >
                      <span className="text-[#a9bb9d] font-mono text-xs mt-0.5 shrink-0">
                        [{i + 1}]
                      </span>
                      <span className="text-[#5a6070] group-hover:text-[#0b1e40] transition-colors leading-relaxed">
                        {r.title}
                        <span className="text-[#5a6070]/50"> — {r.journal}</span>
                        <ExternalLink className="w-3 h-3 inline ml-1.5 opacity-0 group-hover:opacity-50 transition-opacity" />
                      </span>
                    </a>
                  ))}
                </div>
              </div>
            </section>

            <Footer />
          </>
        )}

        {/* ════════════════════════════════════
            ANALYZING
        ════════════════════════════════════ */}
        {step === "analyzing" && (
          <div className="flex flex-col items-center justify-center min-h-[70vh] py-20">
            <video
              src="/loader.webm"
              autoPlay
              muted
              loop
              playsInline
              className="w-[130px] h-[130px] object-contain mb-8"
            />
            <h3 className="text-xl font-medium text-[#0b1e40] mb-2">
              Analyzing genetics…
            </h3>
            <p className="text-sm text-[#5a6070] max-w-sm text-center leading-relaxed">
              Modeling Mendelian inheritance across pharmacogenomic variants.
              This usually takes a few seconds.
            </p>
          </div>
        )}

        {/* ════════════════════════════════════
            RESULTS
        ════════════════════════════════════ */}
        {step === "results" && results && (
          <div className="pt-24 pb-16 px-4 sm:px-6">
            <div className="max-w-5xl mx-auto">
              <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
                <CompatibilityReport
                  results={results.compatibility}
                  aiSummary={results.ai_summary}
                />
              </motion.div>
            </div>
          </div>
        )}
      </div>
    </ProtectedRoute>
  );
}
